Algoritmo "APP Converter Celcius em Fahrenheit"

Var

   celcius, fahr : real


Inicio

      escreval("APP Corverte °C em °F")
      escreval("=============================")
      escreval("")

      escreva("Digite a temperatura em °C: ")
      leia (celcius)
      
      fahr <- ((celcius * 9) / 5) + 32
      
      escreval("")
      escreva("A temperatura em Fahrenheit é: ", fahr, "°F")



Fimalgoritmo