Algoritmo "APP Calcula o Dobro e o Triplo"

Var

   numero, dobro, triplo : inteiro


Inicio

      escreval("APP Calcula Dobro & Triplo")
      escreval("=============================")
      escreval("")
      
      escreva("Digite um número: ")
      leia(numero)
      
      dobro <- (numero * 2)
      triplo <- (numero * 3)


      escreval("")
      
      escreva("O dobro do número é ", dobro, " e o triplo é ", triplo)




Fimalgoritmo