Algoritmo "APP Calcula SALÁRIO"

Var

   salario, calc : real


Inicio

      escreval("APP Calcula sALÁRIO")
      escreval("=============================")
      escreval("")
      
      escreva("Digite o valor do salário: ")
      leia(salario)
      
      calc <- (salario + salario * 0.30)



      escreval("")
      
      escreva("O valor do salário com aumento de 30% é: ", calc)




Fimalgoritmo