Algoritmo "Aula01_Ex02"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
//
// Data atual  : 11/05/2022
Var

n1: real
n2: real
soma: real


Inicio

escreval ("Segundo Execício - Soma de dois números")
escreval ("===========================")

escreval ("Digite o primeiro número")
leia(n1)
escreval ("Digite o segundo número")
leia(n2)

soma <- (n1 + n2)

escreva ("A soma dos números é:", soma)


Fimalgoritmo