Algoritmo "Aula01_Ex03"
//
// Data atual  : 11/05/2022
Var

base: real
altura: real
area: real


Inicio

escreval ("Terceiro Execício - Calcular a área do triângiulo")
escreval ("====================================================")

escreval ("Digite a base:")
leia(base)
escreval ("Digite a altura:")
leia(altura)

area <- (base * altura)/2

escreva ("A base do triângulo é:", area)


Fimalgoritmo