Algoritmo "Calcular Idade"

Var
anoAtual, anoNascimento, idade : inteiro

Inicio
      escreval ("App Calcular Idade")
      escreval ("===========================")
      escreval ("")
      escreva ("Digite o ano atual: ")
      leia(anoAtual)
      escreva ("Digite seu ano de nascimento: ")
      leia(anoNascimento)
      
      idade <- (anoAtual - anoNascimento)
      
      escreval("")
      escreval ("Sua idade é: ", idade, " Anos")


Fimalgoritmo